export const data = [
    {
        "position": 1,
        "product_id":
            "1001580411",
        "title":
            "Mix & Match Conley Chili Sling Stacking Patio Dining Chair",
        "thumbnails":
            [
                [
                    "https://images.homedepot.ca/productimages/p_1001580411.jpg?product-images=s",
                    "https://images.homedepot.ca/productimages/p_1001580411.jpg?product-images=m",
                    "https://images.homedepot.ca/productimages/p_1001580411.jpg?product-images=l"
                ]
            ],
        "link":
            "https://www.homedepot.ca/product/stylewell-mix-match-conley-chili-sling-stacking-patio-dining-chair/1001580411",
        "model_number":
            "FCS00015J-CHILI",
        "brand":
            "StyleWell",
        "base_product_code":
            "base-70002430-54-1001025293",
        "variants":
            [
                {
                    "title":
                        "Medium Dark Red",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Medium_Dark_Red.jpg",
                    "link":
                        "https://www.homedepot.ca/product/stylewell-mix-match-conley-chili-sling-stacking-patio-dining-chair/1001580411",
                    "category_code":
                        "vvc-cls_l5-diningchairs-attribute_id_ssku_seatcushioncolour-hd1-7-medium-dark-red"
                },
                {
                    "title":
                        "Dark Slate-Grey",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Dark_Slate-Grey.jpg",
                    "link":
                        "https://www.homedepot.ca/product/stylewell-mix-match-graphite-sling-stacking-patio-dining-chair/1001580444",
                    "category_code":
                        "vvc-cls_l5-diningchairs-attribute_id_ssku_seatcushioncolour-hdcn-11-dark-slate-grey"
                },
                {
                    "title":
                        "Taupe",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Taupe.jpg",
                    "link":
                        "https://www.homedepot.ca/product/stylewell-mix-match-riverbed-sling-stacking-patio-dining-chair/1001580445",
                    "category_code":
                        "vvc-cls_l5-diningchairs-attribute_id_ssku_seatcushioncolour-hdwn-3-taupe"
                }
            ],
        "rating":
            4.588600158691406,
        "reviews":
            474,
        "price":
            24.73,
        "currency":
            "CAD",
        "aisle":
            "LC",
        "badges":
            [
                "CLR"
            ],
        "add_to_cart":
            true,
        "pickup":
        {
            "out_of_stock":
                true
        },
        "delivery":
        {
            "free":
                true,
            "free_delivery_threshold":
                false
        },
        "stock_information":
        {
            "general_stock":
                1,
            "general_stock_status":
                "In Stock",
            "store_stock":
                0,
            "store_stock_status":
                "Out Of Stock"
        }
    },
    {
        "position":
            2,
        "product_id":
            "1000862040",
        "title":
            "Muskoka Contour Chair in Red",
        "thumbnails":
            [
                [
                    "https://images.homedepot.ca/productimages/p_1000862040.jpg?product-images=s",
                    "https://images.homedepot.ca/productimages/p_1000862040.jpg?product-images=m",
                    "https://images.homedepot.ca/productimages/p_1000862040.jpg?product-images=l"
                ]
            ],
        "link":
            "https://www.homedepot.ca/product/gracious-living-muskoka-contour-chair-in-red/1000862040",
        "model_number":
            "11549-20",
        "brand":
            "Gracious Living",
        "base_product_code":
            "base-70001274-11-1000862040",
        "variants":
            [
                {
                    "title":
                        "Red",
                    "type":
                        "Swatch Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Red.jpg",
                    "link":
                        "https://www.homedepot.ca/product/gracious-living-muskoka-contour-chair-in-red/1000862040",
                    "category_code":
                        "vvc-cls_l5-muskokachairs-attribute_id_ssku_colourfamily-hd1-6-red"
                },
                {
                    "title":
                        "Light Teal",
                    "type":
                        "Swatch Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Light_Teal.jpg",
                    "link":
                        "https://www.homedepot.ca/product/gracious-living-muskoka-contour-chair-in-teal/1001030330",
                    "category_code":
                        "vvc-cls_l5-muskokachairs-attribute_id_ssku_colourfamily-hd15b-6-light-teal"
                }
            ],
        "rating":
            4.592100143432617,
        "reviews":
            277,
        "price":
            29.98,
        "currency":
            "CAD",
        "aisle":
            "SA",
        "badges":
            [
                "SB"
            ],
        "add_to_cart":
            true,
        "buy_online_pay_in_store":
            true,
        "pickup":
        {
            "out_of_stock":
                true
        },
        "delivery":
        {
            "schedule_delivery":
                true
        },
        "check_nearby_stores":
            true,
        "stock_information":
        {
            "general_stock":
                0,
            "general_stock_status":
                "Out Of Stock",
            "store_stock":
                0,
            "store_stock_status":
                "Out Of Stock"
        }
    },
    {
        "position":
            3,
        "product_id":
            "1001075724",
        "title":
            "Multi-Position Zero Gravity Patio Lounge Chair in Red",
        "thumbnails":
            [
                [
                    "https://images.homedepot.ca/productimages/p_1001075724.jpg?product-images=s",
                    "https://images.homedepot.ca/productimages/p_1001075724.jpg?product-images=m",
                    "https://images.homedepot.ca/productimages/p_1001075724.jpg?product-images=l"
                ]
            ],
        "link":
            "https://www.homedepot.ca/product/hdg-35-4-inch-w-x-25-5-inch-l-x-44-4-inch-h-multi-position-zero-gravity-patio-lounge-chair-in-red/1001075724",
        "model_number":
            "JCA-OXSS-R",
        "brand":
            "HDG",
        "base_product_code":
            "base-70005415-13-1001075724",
        "variants":
            [
                {
                    "title":
                        "Red",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_RED.jpg",
                    "link":
                        "https://www.homedepot.ca/product/hdg-35-4-inch-w-x-25-5-inch-l-x-44-4-inch-h-multi-position-zero-gravity-patio-lounge-chair-in-red/1001075724",
                    "category_code":
                        "vvc-cls_l5-conversationchairs-attribute_id_ssku_seatcushioncolour-red"
                },
                {
                    "title":
                        "Dark Dusk-Blue",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Dark_Dusk-Blue.jpg",
                    "link":
                        "https://www.homedepot.ca/product/hdg-35-4-inch-w-x-25-5-inch-l-x-44-4-inch-h-multi-position-zero-gravity-lounge-chair-in-blue/1001580616",
                    "category_code":
                        "vvc-cls_l5-conversationchairs-attribute_id_ssku_seatcushioncolour-hd18-8-dark-dusk-blue"
                },
                {
                    "title":
                        "Light Slate-Grey",
                    "type":
                        "Seat / Cushion Colour",
                    "thumbnail":
                        "https://images.homedepot.ca/productimages/swatchImage_Light_Slate-Grey.jpg",
                    "link":
                        "https://www.homedepot.ca/product/hdg-multi-position-zero-gravity-lounge-chair-in-grey/1001075723",
                    "category_code":
                        "vvc-cls_l5-conversationchairs-attribute_id_ssku_seatcushioncolour-hdcn-8-light-slate-grey"
                }
            ],
        "rating":
            4.444699764251709,
        "reviews":
            506,
        "price":
            49.98,
        "currency":
            "CAD",
        "aisle":
            "SS",
        "add_to_cart":
            true,
        "buy_online_pay_in_store":
            true,
        "pickup":
        {
            "out_of_stock":
                true
        },
        "delivery":
        {
            "schedule_delivery":
                true
        },
        "check_nearby_stores":
            true,
        "stock_information":
        {
            "general_stock":
                0,
            "general_stock_status":
                "Out Of Stock",
            "store_stock":
                0,
            "store_stock_status":
                "Out Of Stock"
        }
    }]